#:schema node_modules/wrangler/config-schema.json
name = "sublink-worker-231"
main = "src/worker.jsx"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "6ed10b4161554c7e85bd9e3613d8fac8" }
]

[assets]
directory = "./public"
